# Source files
SRCS = $(wildcard $/*.cpp)
OBJS = $(patsubst $/%.cpp, $/%.o, $(SRCS))

# Executable name
TARGET = $(BIN_DIR)/Dungeon

# Default target
all: $(TARGET)

# Link the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Compile source files to object files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# Clean up build files
clean:
	rm -f $(OBJ_DIR)/*.o $(TARGET)

.PHONY: all clean